.\" test man page source
.\"
.\" use
.\"   groff -man -Tutf8 myautomake.1
.\" or
.\"   nroff -man myautomake.1
.\" to process this source
.\"
.TH MYAUTOMAKE 1 2017-07-07 XYZ "myautomake user manual"
.SH NAME
myautomake \- print information about functions
.SH SYNOPSIS
.B myautomake
[-v | --version] [-h | --help]
.SH DESCRIPTION
.B myautomake
My description 
.P
.fi
.SH OPTIONS
.IP "-v or --version"
show version and copyright
.IP "-h or --help"
display this help and exit
.SH RETURN VALUE
.IP 1
unknown or invalid argument on invocation
.IP 0
successful program execution
.SH "SEE ALSO"
.BR abc (1)

